# Generated by Django 3.2.9 on 2022-01-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seen_news',
            field=models.BooleanField(default=False, verbose_name='Is user seen last news on main page'),
        ),
    ]
