# Generated by Django 3.2.9 on 2022-01-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0002_user_seen_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_vip',
            new_name='is_member',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is user currently active'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
