# Generated by Django 3.2.9 on 2022-01-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0008_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('thing_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='INT ID of the thing')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Name of the thing')),
                ('description', models.TextField(verbose_name='Description of the thing')),
                ('files_links', models.TextField(blank=True, verbose_name="List of the thing's files with separators")),
            ],
        ),
    ]
