# Generated by Django 3.2.9 on 2022-01-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0009_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='author',
            field=models.CharField(default='Аноним', max_length=25, verbose_name="Name of the thing's author"),
        ),
    ]
