# Generated by Django 3.2.9 on 2022-01-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0010_thing_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaRoom',
            fields=[
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Name of the room')),
                ('login_only', models.BooleanField(verbose_name='Only members can join the room')),
                ('users_in', models.CharField(blank=True, max_length=500, verbose_name='Users currently in room')),
                ('admin', models.CharField(blank=True, max_length=100, null=True, verbose_name="Room admin's channel name")),
                ('room_id', models.CharField(default='84c133f38b36d4d02e6d', max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='HEX-ID of the room')),
            ],
        ),
    ]
