# Generated by Django 3.2.9 on 2022-01-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0011_cinemaroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaroom',
            name='room_id',
            field=models.CharField(default='8dc4d7c3bab9c5315c67', max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='HEX-ID of the room'),
        ),
        migrations.AlterField(
            model_name='cinemaroom',
            name='users_in',
            field=models.CharField(blank=True, default='[]', max_length=2500, verbose_name='Users currently in room'),
        ),
    ]
