# Generated by Django 3.2.9 on 2022-01-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0013_alter_cinemaroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemaroom',
            name='room_id',
            field=models.CharField(default='6049cf40b40c4cedc385', max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='HEX-ID of the room'),
        ),
    ]
