# Generated by Django 3.2.9 on 2022-01-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0014_alter_cinemaroom_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaroom',
            name='messages',
            field=models.TextField(default='[]', verbose_name="Messages in this room's chat"),
        ),
        migrations.AlterField(
            model_name='cinemaroom',
            name='admin',
            field=models.CharField(max_length=100, null=True, verbose_name="Room admin's channel name"),
        ),
        migrations.AlterField(
            model_name='cinemaroom',
            name='room_id',
            field=models.CharField(default='3aa0bad8d56643b73cb0', max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='HEX-ID of the room'),
        ),
        migrations.AlterField(
            model_name='cinemaroom',
            name='users_in',
            field=models.TextField(default='[]', verbose_name='Users currently in room'),
        ),
    ]
