# Generated by Django 3.2.9 on 2022-01-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0016_auto_20220120_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemaroom',
            name='waiting_users',
        ),
    ]
