# Generated by Django 3.2.9 on 2022-01-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0017_remove_cinemaroom_waiting_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaroom',
            name='state',
            field=models.CharField(default='paused', max_length=20, verbose_name='Currently playing video state'),
        ),
        migrations.AddField(
            model_name='cinemaroom',
            name='time',
            field=models.FloatField(default=0.0, verbose_name='Currently playing video time'),
        ),
        migrations.AddField(
            model_name='cinemaroom',
            name='video',
            field=models.CharField(max_length=100, null=True, verbose_name='Currently playing video link'),
        ),
    ]
