# Generated by Django 3.2.11 on 2022-01-23 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0018_auto_20220120_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemaroom',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cinemaroom',
            name='time',
        ),
        migrations.RemoveField(
            model_name='cinemaroom',
            name='video',
        ),
    ]
