# Generated by Django 3.2.11 on 2022-01-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yobaclub', '0019_auto_20220123_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemaroom',
            name='waiting_users',
            field=models.TextField(default='[]', verbose_name='New users, waiting for state'),
        ),
    ]
